// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TayeeProtoBuf.proto

package com.tayee.game.texas;

public final class GameProtoBuf {
  private GameProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.tayee.game.texas.MsgCode}
   */
  public enum MsgCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CODE_OK = 200;</code>
     */
    CODE_OK(0, 200),
    /**
     * <code>CODE_ERR = 500;</code>
     */
    CODE_ERR(1, 500),
    ;

    /**
     * <code>CODE_OK = 200;</code>
     */
    public static final int CODE_OK_VALUE = 200;
    /**
     * <code>CODE_ERR = 500;</code>
     */
    public static final int CODE_ERR_VALUE = 500;


    public final int getNumber() { return value; }

    public static MsgCode valueOf(int value) {
      switch (value) {
        case 200: return CODE_OK;
        case 500: return CODE_ERR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
            public MsgCode findValueByNumber(int number) {
              return MsgCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tayee.game.texas.GameProtoBuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgCode[] VALUES = values();

    public static MsgCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.tayee.game.texas.MsgCode)
  }

  /**
   * Protobuf enum {@code com.tayee.game.texas.MsgMk}
   */
  public enum MsgMk
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MK_PLAYER = 10000;</code>
     */
    MK_PLAYER(0, 10000),
    /**
     * <code>MK_MATCH = 20000;</code>
     */
    MK_MATCH(1, 20000),
    ;

    /**
     * <code>MK_PLAYER = 10000;</code>
     */
    public static final int MK_PLAYER_VALUE = 10000;
    /**
     * <code>MK_MATCH = 20000;</code>
     */
    public static final int MK_MATCH_VALUE = 20000;


    public final int getNumber() { return value; }

    public static MsgMk valueOf(int value) {
      switch (value) {
        case 10000: return MK_PLAYER;
        case 20000: return MK_MATCH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgMk>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgMk>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgMk>() {
            public MsgMk findValueByNumber(int number) {
              return MsgMk.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tayee.game.texas.GameProtoBuf.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgMk[] VALUES = values();

    public static MsgMk valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgMk(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.tayee.game.texas.MsgMk)
  }

  /**
   * Protobuf enum {@code com.tayee.game.texas.MsgCmd}
   */
  public enum MsgCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CMD_BUILD_PLAYER = 10001;</code>
     */
    CMD_BUILD_PLAYER(0, 10001),
    /**
     * <code>CMD_ENTER_GAME = 10002;</code>
     */
    CMD_ENTER_GAME(1, 10002),
    /**
     * <code>CMD_SAVE_DATA = 10003;</code>
     */
    CMD_SAVE_DATA(2, 10003),
    /**
     * <code>CMD_LOAD_RANK = 10004;</code>
     */
    CMD_LOAD_RANK(3, 10004),
    /**
     * <code>CMD_HEART_BEAT = 19998;</code>
     */
    CMD_HEART_BEAT(4, 19998),
    /**
     * <code>CMD_EXIT_GAME = 19999;</code>
     */
    CMD_EXIT_GAME(5, 19999),
    /**
     * <code>CMD_RANDOM_MATCH = 20001;</code>
     */
    CMD_RANDOM_MATCH(6, 20001),
    /**
     * <code>CMD_ENTER_MATCH = 20002;</code>
     */
    CMD_ENTER_MATCH(7, 20002),
    /**
     * <code>CMD_BUILD_MATCH = 20003;</code>
     */
    CMD_BUILD_MATCH(8, 20003),
    /**
     * <code>CMD_ACTION_MATCH = 20004;</code>
     */
    CMD_ACTION_MATCH(9, 20004),
    /**
     * <code>CMD_ACTION_PLAYER = 20005;</code>
     */
    CMD_ACTION_PLAYER(10, 20005),
    ;

    /**
     * <code>CMD_BUILD_PLAYER = 10001;</code>
     */
    public static final int CMD_BUILD_PLAYER_VALUE = 10001;
    /**
     * <code>CMD_ENTER_GAME = 10002;</code>
     */
    public static final int CMD_ENTER_GAME_VALUE = 10002;
    /**
     * <code>CMD_SAVE_DATA = 10003;</code>
     */
    public static final int CMD_SAVE_DATA_VALUE = 10003;
    /**
     * <code>CMD_LOAD_RANK = 10004;</code>
     */
    public static final int CMD_LOAD_RANK_VALUE = 10004;
    /**
     * <code>CMD_HEART_BEAT = 19998;</code>
     */
    public static final int CMD_HEART_BEAT_VALUE = 19998;
    /**
     * <code>CMD_EXIT_GAME = 19999;</code>
     */
    public static final int CMD_EXIT_GAME_VALUE = 19999;
    /**
     * <code>CMD_RANDOM_MATCH = 20001;</code>
     */
    public static final int CMD_RANDOM_MATCH_VALUE = 20001;
    /**
     * <code>CMD_ENTER_MATCH = 20002;</code>
     */
    public static final int CMD_ENTER_MATCH_VALUE = 20002;
    /**
     * <code>CMD_BUILD_MATCH = 20003;</code>
     */
    public static final int CMD_BUILD_MATCH_VALUE = 20003;
    /**
     * <code>CMD_ACTION_MATCH = 20004;</code>
     */
    public static final int CMD_ACTION_MATCH_VALUE = 20004;
    /**
     * <code>CMD_ACTION_PLAYER = 20005;</code>
     */
    public static final int CMD_ACTION_PLAYER_VALUE = 20005;


    public final int getNumber() { return value; }

    public static MsgCmd valueOf(int value) {
      switch (value) {
        case 10001: return CMD_BUILD_PLAYER;
        case 10002: return CMD_ENTER_GAME;
        case 10003: return CMD_SAVE_DATA;
        case 10004: return CMD_LOAD_RANK;
        case 19998: return CMD_HEART_BEAT;
        case 19999: return CMD_EXIT_GAME;
        case 20001: return CMD_RANDOM_MATCH;
        case 20002: return CMD_ENTER_MATCH;
        case 20003: return CMD_BUILD_MATCH;
        case 20004: return CMD_ACTION_MATCH;
        case 20005: return CMD_ACTION_PLAYER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgCmd>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCmd>() {
            public MsgCmd findValueByNumber(int number) {
              return MsgCmd.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tayee.game.texas.GameProtoBuf.getDescriptor().getEnumTypes().get(2);
    }

    private static final MsgCmd[] VALUES = values();

    public static MsgCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgCmd(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.tayee.game.texas.MsgCmd)
  }

  public interface MsgRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tayee.game.texas.MsgRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>required int32 mk = 2;</code>
     */
    boolean hasMk();
    /**
     * <code>required int32 mk = 2;</code>
     */
    int getMk();

    /**
     * <code>required int32 cmd = 3;</code>
     */
    boolean hasCmd();
    /**
     * <code>required int32 cmd = 3;</code>
     */
    int getCmd();

    /**
     * <code>required string param = 4;</code>
     */
    boolean hasParam();
    /**
     * <code>required string param = 4;</code>
     */
    java.lang.String getParam();
    /**
     * <code>required string param = 4;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();
  }
  /**
   * Protobuf type {@code com.tayee.game.texas.MsgRequest}
   */
  public static final class MsgRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tayee.game.texas.MsgRequest)
      MsgRequestOrBuilder {
    // Use MsgRequest.newBuilder() to construct.
    private MsgRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgRequest defaultInstance;
    public static MsgRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MsgRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              token_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              mk_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cmd_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              param_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tayee.game.texas.GameProtoBuf.MsgRequest.class, com.tayee.game.texas.GameProtoBuf.MsgRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgRequest> PARSER =
        new com.google.protobuf.AbstractParser<MsgRequest>() {
      public MsgRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>required string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MK_FIELD_NUMBER = 2;
    private int mk_;
    /**
     * <code>required int32 mk = 2;</code>
     */
    public boolean hasMk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 mk = 2;</code>
     */
    public int getMk() {
      return mk_;
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <code>required int32 cmd = 3;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 cmd = 3;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int PARAM_FIELD_NUMBER = 4;
    private java.lang.Object param_;
    /**
     * <code>required string param = 4;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string param = 4;</code>
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string param = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      token_ = "";
      mk_ = 0;
      cmd_ = 0;
      param_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, mk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getParamBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, mk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getParamBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tayee.game.texas.GameProtoBuf.MsgRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tayee.game.texas.MsgRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tayee.game.texas.MsgRequest)
        com.tayee.game.texas.GameProtoBuf.MsgRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tayee.game.texas.GameProtoBuf.MsgRequest.class, com.tayee.game.texas.GameProtoBuf.MsgRequest.Builder.class);
      }

      // Construct using com.tayee.game.texas.GameProtoBuf.MsgRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mk_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgRequest_descriptor;
      }

      public com.tayee.game.texas.GameProtoBuf.MsgRequest getDefaultInstanceForType() {
        return com.tayee.game.texas.GameProtoBuf.MsgRequest.getDefaultInstance();
      }

      public com.tayee.game.texas.GameProtoBuf.MsgRequest build() {
        com.tayee.game.texas.GameProtoBuf.MsgRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tayee.game.texas.GameProtoBuf.MsgRequest buildPartial() {
        com.tayee.game.texas.GameProtoBuf.MsgRequest result = new com.tayee.game.texas.GameProtoBuf.MsgRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mk_ = mk_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.param_ = param_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tayee.game.texas.GameProtoBuf.MsgRequest) {
          return mergeFrom((com.tayee.game.texas.GameProtoBuf.MsgRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tayee.game.texas.GameProtoBuf.MsgRequest other) {
        if (other == com.tayee.game.texas.GameProtoBuf.MsgRequest.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasMk()) {
          setMk(other.getMk());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasParam()) {
          bitField0_ |= 0x00000008;
          param_ = other.param_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        if (!hasMk()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasParam()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tayee.game.texas.GameProtoBuf.MsgRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tayee.game.texas.GameProtoBuf.MsgRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      private int mk_ ;
      /**
       * <code>required int32 mk = 2;</code>
       */
      public boolean hasMk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 mk = 2;</code>
       */
      public int getMk() {
        return mk_;
      }
      /**
       * <code>required int32 mk = 2;</code>
       */
      public Builder setMk(int value) {
        bitField0_ |= 0x00000002;
        mk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mk = 2;</code>
       */
      public Builder clearMk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mk_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ ;
      /**
       * <code>required int32 cmd = 3;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 cmd = 3;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required int32 cmd = 3;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmd = 3;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object param_ = "";
      /**
       * <code>required string param = 4;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string param = 4;</code>
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            param_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string param = 4;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string param = 4;</code>
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string param = 4;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000008);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <code>required string param = 4;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        param_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tayee.game.texas.MsgRequest)
    }

    static {
      defaultInstance = new MsgRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tayee.game.texas.MsgRequest)
  }

  public interface MsgResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tayee.game.texas.MsgResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>required string data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code com.tayee.game.texas.MsgResponse}
   */
  public static final class MsgResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tayee.game.texas.MsgResponse)
      MsgResponseOrBuilder {
    // Use MsgResponse.newBuilder() to construct.
    private MsgResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgResponse defaultInstance;
    public static MsgResponse getDefaultInstance() {
      return defaultInstance;
    }

    public MsgResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              data_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tayee.game.texas.GameProtoBuf.MsgResponse.class, com.tayee.game.texas.GameProtoBuf.MsgResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgResponse> PARSER =
        new com.google.protobuf.AbstractParser<MsgResponse>() {
      public MsgResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.lang.Object data_;
    /**
     * <code>required string data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = 0;
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tayee.game.texas.GameProtoBuf.MsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tayee.game.texas.GameProtoBuf.MsgResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tayee.game.texas.MsgResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tayee.game.texas.MsgResponse)
        com.tayee.game.texas.GameProtoBuf.MsgResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tayee.game.texas.GameProtoBuf.MsgResponse.class, com.tayee.game.texas.GameProtoBuf.MsgResponse.Builder.class);
      }

      // Construct using com.tayee.game.texas.GameProtoBuf.MsgResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tayee.game.texas.GameProtoBuf.internal_static_com_tayee_game_texas_MsgResponse_descriptor;
      }

      public com.tayee.game.texas.GameProtoBuf.MsgResponse getDefaultInstanceForType() {
        return com.tayee.game.texas.GameProtoBuf.MsgResponse.getDefaultInstance();
      }

      public com.tayee.game.texas.GameProtoBuf.MsgResponse build() {
        com.tayee.game.texas.GameProtoBuf.MsgResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tayee.game.texas.GameProtoBuf.MsgResponse buildPartial() {
        com.tayee.game.texas.GameProtoBuf.MsgResponse result = new com.tayee.game.texas.GameProtoBuf.MsgResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tayee.game.texas.GameProtoBuf.MsgResponse) {
          return mergeFrom((com.tayee.game.texas.GameProtoBuf.MsgResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tayee.game.texas.GameProtoBuf.MsgResponse other) {
        if (other == com.tayee.game.texas.GameProtoBuf.MsgResponse.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tayee.game.texas.GameProtoBuf.MsgResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tayee.game.texas.GameProtoBuf.MsgResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tayee.game.texas.MsgResponse)
    }

    static {
      defaultInstance = new MsgResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tayee.game.texas.MsgResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tayee_game_texas_MsgRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tayee_game_texas_MsgRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tayee_game_texas_MsgResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tayee_game_texas_MsgResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TayeeProtoBuf.proto\022\024com.tayee.game.te" +
      "xas\"C\n\nMsgRequest\022\r\n\005token\030\001 \002(\t\022\n\n\002mk\030\002" +
      " \002(\005\022\013\n\003cmd\030\003 \002(\005\022\r\n\005param\030\004 \002(\t\")\n\013MsgR" +
      "esponse\022\014\n\004code\030\001 \002(\005\022\014\n\004data\030\002 \002(\t*&\n\007M" +
      "sgCode\022\014\n\007CODE_OK\020\310\001\022\r\n\010CODE_ERR\020\364\003*\'\n\005M" +
      "sgMk\022\016\n\tMK_PLAYER\020\220N\022\016\n\010MK_MATCH\020\240\234\001*\376\001\n" +
      "\006MsgCmd\022\025\n\020CMD_BUILD_PLAYER\020\221N\022\023\n\016CMD_EN" +
      "TER_GAME\020\222N\022\022\n\rCMD_SAVE_DATA\020\223N\022\022\n\rCMD_L" +
      "OAD_RANK\020\224N\022\024\n\016CMD_HEART_BEAT\020\236\234\001\022\023\n\rCMD" +
      "_EXIT_GAME\020\237\234\001\022\026\n\020CMD_RANDOM_MATCH\020\241\234\001\022\025",
      "\n\017CMD_ENTER_MATCH\020\242\234\001\022\025\n\017CMD_BUILD_MATCH" +
      "\020\243\234\001\022\026\n\020CMD_ACTION_MATCH\020\244\234\001\022\027\n\021CMD_ACTI" +
      "ON_PLAYER\020\245\234\001B\016B\014GameProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tayee_game_texas_MsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tayee_game_texas_MsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tayee_game_texas_MsgRequest_descriptor,
        new java.lang.String[] { "Token", "Mk", "Cmd", "Param", });
    internal_static_com_tayee_game_texas_MsgResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tayee_game_texas_MsgResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tayee_game_texas_MsgResponse_descriptor,
        new java.lang.String[] { "Code", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
